# DB credentials are generated by Terraform and stored only in Secrets Manager.
# The application reads them at runtime; they never appear in code or user_data.

resource "random_password" "db" {
  length           = 24
  special          = true
  override_special = "!#%^*()-_=+[]{}:?" # RDS forbids / @ " and space
}

resource "aws_secretsmanager_secret" "db" {
  name                    = "${var.name_prefix}/rds/mysql"
  description             = "RDS MySQL credentials for ${var.name_prefix}"
  recovery_window_in_days = var.recovery_window_in_days
}

resource "aws_secretsmanager_secret_version" "db" {
  secret_id = aws_secretsmanager_secret.db.id

  secret_string = jsonencode({
    engine   = "mysql"
    username = var.db_username
    password = random_password.db.result
    host     = var.db_host
    port     = var.db_port
    dbname   = var.db_name
  })
}
